In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (20, 6)
plt.rcParams['font.size'] = 14
import pandas as pd

In [2]:
df = pd.read_csv('../data/adult.data', index_col=False)

In [3]:
golden = pd.read_csv('../data/crx.test', index_col=False)

The `golden` dataframe is a "golden" test set that can be used to verify the performance of the model.

In [4]:
golden.head()

age   workclass  fnlwgt      education  education-num       marital-status  \
0   25     Private  226802           11th              7        Never-married   
1   38     Private   89814        HS-grad              9   Married-civ-spouse   
2   28   Local-gov  336951     Assoc-acdm             12   Married-civ-spouse   
3   44     Private  160323   Some-college             10   Married-civ-spouse   
4   18           ?  103497   Some-college             10        Never-married   

           occupation relationship    race      sex  capital-gain  \
0   Machine-op-inspct    Own-child   Black     Male             0   
1     Farming-fishing      Husband   White     Male             0   
2     Protective-serv      Husband   White     Male             0   
3   Machine-op-inspct      Husband   Black     Male          7688   
4                   ?    Own-child   White   Female             0   

   capital-loss  hours-per-week  native-country   salary  
0             0              40   United-States   <=50K.  
1             0              50   United-States   <=50K.  
2             0              40   United-States    >50K.  
3             0              40   United-States    >50K.  
4             0              30   United-States   <=50K.

In [5]:
df.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [6]:
df['salary'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [7]:
df.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [8]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'salary'],
      dtype='object')

In [10]:
non_numeric_columns = ['workclass', 'education', 'marital-status', 
                     'occupation', 'relationship', 'race', 'sex', 
                     'native-country', 'fnlwgt']

In [10]:
# from sklearn import preprocessing

# enc = preprocessing.OrdinalEncoder()

# pd.get_dummies(df[transform_columns]).head()

In [17]:
x = df.copy().drop(non_numeric_columns, axis=1)

In [18]:
# x = pd.concat([x.drop(transform_columns, axis=1), 
#                pd.get_dummies(df[transform_columns])], axis=1,)

# x["salary"] = enc.fit_transform(df[["salary"]])
# enc.categories_

In [19]:
xt = golden.copy().drop(non_numeric_columns, axis=1)

In [14]:
# xt = pd.concat([xt.drop(transform_columns, axis=1), 
#                pd.get_dummies(golden[transform_columns])], axis=1,)

# xt["salary"] = enc.fit_transform(golden[["salary"]])

In [56]:
x['salary'] = x.salary.str.contains('>').astype(int)

In [57]:
xt['salary'] = xt.salary.str.contains('>').astype(int)

In [58]:
xt.salary.value_counts()

0    12435
1     3846
Name: salary, dtype: int64

In [20]:
# from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
# from sklearn.ensemble import RandomForestClassifier as Model
# model = Model()

#### For now we choose the DecisionTree as our classifier. More details next class about Decision Trees

In [59]:
model = DecisionTreeClassifier(criterion='entropy')

In [60]:
model.fit(x.drop(['salary'], axis=1), x.salary)

DecisionTreeClassifier(criterion='entropy')

In [96]:
list(zip(x.drop(['salary'], axis=1).columns, model.feature_importances_))

[('age', 0.3273649225519472),
 ('education-num', 0.16738222136569186),
 ('capital-gain', 0.2477000049540546),
 ('capital-loss', 0.09749796337984631),
 ('hours-per-week', 0.16005488774846008)]

In [26]:
x.drop(['salary'] , axis=1).head()

age  education-num  capital-gain  capital-loss  hours-per-week
0   39             13          2174             0              40
1   50             13             0             0              13
2   38              9             0             0              40
3   53              7             0             0              40
4   28             13             0             0              40

In [62]:
set(x.columns) - set(xt.columns)

set()

In [88]:
predictions = model.predict(xt.drop(['salary'], axis=1))

In [64]:
predictions_train = model.predict(x.drop(['salary'], axis=1))

In [65]:
xt.drop(['salary'], axis=1).head()

age  education-num  capital-gain  capital-loss  hours-per-week
0   25              7             0             0              40
1   38              9             0             0              50
2   28             12             0             0              40
3   44             10          7688             0              40
4   18             10             0             0              30

### Here we use the metrics to calculate how well our model is performing.
- accuracy = number correct / total number
- precision = number of correct 1 (or 0) / number of 1s (or 0s) the model predicted
- recall = number of correct 1s (or 0s) / number of 1s (or 0s) that exist in the dataset
- f1 = 2 * prec * recall / (prec+recall)

In [66]:
from sklearn.metrics import (accuracy_score, 
                             classification_report, 
                             confusion_matrix, auc, roc_curve
                            )

In [67]:
import numpy as np

In [84]:
predictions = np.zeros(16281)
predictions

array([0., 0., 0., ..., 0., 0., 0.])

In [69]:
accuracy_score(xt.salary, predictions)

0.7637737239727289

In [70]:
accuracy_score(xt.salary, predictions)

0.7637737239727289

In [80]:
predictions.shape, xt.salary.values.shape

((16281,), (16281,))

In [81]:
(xt.salary.values == predictions).sum()/len(predictions)

0.7637737239727289

In [90]:
np.logical_and(xt.salary.values, predictions).sum()

1777

In [93]:
confusion_matrix(xt.salary, predictions)

array([[11516,   919],
       [ 2069,  1777]])

In [94]:
11531/(11531+2077), 1769/(1769+904), 1769/(1769+2077), 11531/(11531+904)

(0.8473691945914168,
 0.6618032173587729,
 0.45995839833593344,
 0.9273019702452754)

In [95]:
print(classification_report(xt.salary, predictions))

              precision    recall  f1-score   support

           0       0.85      0.93      0.89     12435
           1       0.66      0.46      0.54      3846

    accuracy                           0.82     16281
   macro avg       0.75      0.69      0.71     16281
weighted avg       0.80      0.82      0.80     16281



In [75]:
2* (.80 *.10)/(.8+.1)

0.1777777777777778

### Can we run this on the training data? What type of scores should we expect?

In [31]:
accuracy_score(x.salary, predictions_train)

0.8841558920180584

In [32]:
confusion_matrix(x.salary, predictions_train)

array([[24136,   584],
       [ 3188,  4653]])

In [33]:
print(classification_report(x.salary, predictions_train))

              precision    recall  f1-score   support

           0       0.88      0.98      0.93     24720
           1       0.89      0.59      0.71      7841

   micro avg       0.88      0.88      0.88     32561
   macro avg       0.89      0.78      0.82     32561
weighted avg       0.88      0.88      0.88     32561



In [34]:
len(x)

32561

# Now we use test_train_split instead of using the golden test set provided to us

In [97]:
from sklearn.model_selection import train_test_split

In [98]:
x_train, x_test, y_train, y_test = train_test_split(x.drop(['salary'], axis=1),x.salary, test_size=.20)

In [99]:
x.shape, x_train.shape, x_test.shape

((32561, 6), (26048, 5), (6513, 5))

In [102]:
model.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [103]:
test_predictions = model.predict(x_test)

In [104]:
accuracy_score(y_test, test_predictions)

0.8212805158912944

In [105]:
confusion_matrix(y_test, test_predictions)

array([[4622,  355],
       [ 809,  727]])

In [106]:
confusion_matrix(xt.salary, predictions)

array([[11516,   919],
       [ 2069,  1777]])

In [107]:
print(classification_report(y_test, test_predictions))

              precision    recall  f1-score   support

           0       0.85      0.93      0.89      4977
           1       0.67      0.47      0.56      1536

    accuracy                           0.82      6513
   macro avg       0.76      0.70      0.72      6513
weighted avg       0.81      0.82      0.81      6513



In [44]:
print(classification_report(xt.salary, predictions))

              precision    recall  f1-score   support

           0       0.85      0.93      0.89     12435
           1       0.66      0.47      0.55      3846

   micro avg       0.82      0.82      0.82     16281
   macro avg       0.75      0.70      0.72     16281
weighted avg       0.80      0.82      0.81     16281



# Using cross_validate to perform n-fold validations

In [108]:
from sklearn.model_selection import cross_validate

In [109]:
cross_validate(model, x.drop(['salary'], axis=1), x.salary, cv=20, 
               scoring=['accuracy', 'recall', 'precision', 'f1'], return_train_score=True)

{'fit_time': array([0.09545207, 0.05216408, 0.04937339, 0.04642582, 0.04876399,
        0.05009604, 0.04885077, 0.0519011 , 0.05646992, 0.05486703,
        0.06152129, 0.05553889, 0.05605817, 0.06149578, 0.04999089,
        0.05305195, 0.08864689, 0.06343102, 0.0541501 , 0.04926419]),
 'score_time': array([0.01071191, 0.00725698, 0.00547767, 0.00675917, 0.00468993,
        0.00534511, 0.00616407, 0.0062418 , 0.00865698, 0.00791502,
        0.0102427 , 0.00580001, 0.00769901, 0.00543308, 0.00467515,
        0.00696802, 0.0124681 , 0.0050118 , 0.00774503, 0.00484467]),
 'test_accuracy': array([0.81399632, 0.82678133, 0.81388206, 0.81879607, 0.81019656,
        0.82555283, 0.80712531, 0.81756757, 0.81326781, 0.81879607,
        0.82371007, 0.81572482, 0.80958231, 0.81203931, 0.82739558,
        0.81265356, 0.81941032, 0.81756757, 0.82002457, 0.80773956]),
 'train_accuracy': array([0.88526445, 0.88410435, 0.88549446, 0.88530049, 0.88504186,
        0.88449229, 0.88507419, 0.88504186, 0.884